{% set data = load_setup_py_data() %}

package:
  name: "pymt_wavewatch3"
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - model_metadata
    - bmi-wavewatch3 
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - bmi-wavewatch3 

test:
  requires:
    - bmi-tester
    - model_metadata
  imports:
    - pymt_wavewatch3
  commands:
    - config_file=$(mmd-stage WaveWatch3 . > MANIFEST && mmd-query WaveWatch3 --var=run.config_file.path)
    - bmi-test pymt_wavewatch3.bmi:WaveWatch3 --config-file=$config_file --manifest=MANIFEST -v

about:
  summary: Python package that wraps the pymt_wavewatch3 BMI.
  home: https://github.com/pymt-lab/pymt_wavewatch3
  license: MIT License
  license_file: LICENSE
  dev_url: https://github.com/pymt-lab/pymt_wavewatch3
