[library."WaveWatch3"]
language = "python"
library = "bmi_wavewatch3"
header = ""
entry_point = "BmiWaveWatch3"


[build]
undef_macros = []
define_macros = []
libraries = []
library_dirs = []
include_dirs = []
extra_compile_args = []

[package]
name = "pymt_wavewatch3"
requirements = ["bmi-wavewatch3"]

[info]
github_username = "pymt-lab"
package_author = "csdms"
package_author_email = "csdms@colorado.edu"
package_license = "MIT License"
summary = "PyMT plugin for WAVEWATCH III"

[ci]
python_version = ["3.9"]
os = ["linux", "mac", "windows"]

